import { Lesson } from "./types";

// Simplified subset of the provided vocabulary for the prompt context
// In a real app, this would be the full list provided in the prompt.
// We are structuring it to be passable to Gemini.

export const vocabFestival = [
  { simplified: "节日", pinyin: "jiérì", definition: "holiday, festival" },
  {
    simplified: "舅舅",
    pinyin: "jiùjiu",
    definition: "uncle (mother's brother)",
  },
  {
    simplified: "舅妈",
    pinyin: "jiùmā",
    definition: "aunt (mother's brother's wife)",
  },
  { simplified: "小区", pinyin: "xiǎoqū", definition: "residential complex" },
  {
    simplified: "环境",
    pinyin: "huánjìng",
    definition: "environment, surroundings",
  },
  { simplified: "除夕", pinyin: "chúxī", definition: "Chinese New Year's Eve" },
  { simplified: "年夜饭", pinyin: "niányèfàn", definition: "CNY Eve dinner" },
  { simplified: "墙", pinyin: "qiáng", definition: "wall" },
  { simplified: "贴", pinyin: "tiē", definition: "to paste, to glue" },
  { simplified: "福", pinyin: "fú", definition: "blessing, good fortune" },
  { simplified: "倒", pinyin: "dào", definition: "to turn upside down" },
  { simplified: "奇怪", pinyin: "qíguài", definition: "strange, weird" },
  { simplified: "意思", pinyin: "yìsi", definition: "meaning" },
  { simplified: "以", pinyin: "yǐ", definition: "with" },
  { simplified: "代", pinyin: "dài", definition: "to replace, substitute" },
  { simplified: "酒", pinyin: "jiǔ", definition: "alcohol, liquor" },
  { simplified: "举", pinyin: "jǔ", definition: "to lift, raise" },
  { simplified: "顺利", pinyin: "shùnlì", definition: "smooth, successful" },
  { simplified: "进步", pinyin: "jìnbù", definition: "to make progress" },
  { simplified: "干杯", pinyin: "gān bēi", definition: "to drink a toast" },
  {
    simplified: "成功",
    pinyin: "chénggōng",
    definition: "to succeed; successful",
  },
  {
    simplified: "晚会",
    pinyin: "wǎnhuì",
    definition: "evening gathering, soiree",
  },
  { simplified: "剩下", pinyin: "shèng xia", definition: "to be left over" },
  { simplified: "浪费", pinyin: "làngfèi", definition: "to waste, squander" },
  { simplified: "余", pinyin: "yú", definition: "surplus" },
  {
    simplified: "传统",
    pinyin: "chuántǒng",
    definition: "tradition; traditional",
  },
  { simplified: "农历", pinyin: "nónglì", definition: "lunar calendar" },
  { simplified: "初", pinyin: "chū", definition: "first, early part of" },
  { simplified: "粽子", pinyin: "zòngzi", definition: "sticky-rice dumpling" },
  { simplified: "月饼", pinyin: "yuèbǐng", definition: "moon cake" },
  { simplified: "团圆", pinyin: "tuányuán", definition: "to reunite" },
  {
    simplified: "正月",
    pinyin: "zhēngyuè",
    definition: "first month of lunar year",
  },
  { simplified: "元宵", pinyin: "yuánxiāo", definition: "sweet dumplings" },
  { simplified: "嘛", pinyin: "ma", definition: "particle for obviousness" },
  { simplified: "计时", pinyin: "jì shí", definition: "to count time" },
  { simplified: "拜年", pinyin: "bài nián", definition: "pay a New Year call" },
  { simplified: "恭喜", pinyin: "gōngxǐ", definition: "to congratulate" },
  { simplified: "发财", pinyin: "fā cái", definition: "to get rich" },
  { simplified: "红包", pinyin: "hóngbāo", definition: "red envelope" },
  { simplified: "热闹", pinyin: "rènao", definition: "lively, buzzing" },
  { simplified: "鞭炮", pinyin: "biānpào", definition: "firecracker" },
  { simplified: "春节", pinyin: "Chūnjié", definition: "Spring Festival" },
  {
    simplified: "端午节",
    pinyin: "Duānwǔjié",
    definition: "Dragon Boat Festival",
  },
  {
    simplified: "中秋节",
    pinyin: "Zhōngqiūjié",
    definition: "Mid-Autumn Festival",
  },
  { simplified: "感恩节", pinyin: "Gǎn’ēnjié", definition: "Thanksgiving" },
  {
    simplified: "元宵节",
    pinyin: "Yuánxiāojié",
    definition: "Lantern Festival",
  },
];

export const vocabChange = [
  { simplified: "变化", pinyin: "biànhuà", definition: "to change, change" },
  { simplified: "末", pinyin: "mò", definition: "end" },
  {
    simplified: "来不及",
    pinyin: "lái bu jí",
    definition: "to not have enough time, to be too late",
  },
  {
    simplified: "高（速）铁（路）",
    pinyin: "gāo(sù) tiě(lù)",
    definition: "high-speed rail",
  },
  { simplified: "表哥", pinyin: "biǎogē", definition: "older male cousin" },
  { simplified: "街", pinyin: "jiē", definition: "street" },
  { simplified: "盖", pinyin: "gài", definition: "to build, to construct" },
  { simplified: "骑", pinyin: "qí", definition: "to ride" },
  { simplified: "自行车", pinyin: "zìxíngchē", definition: "bicycle" },
  {
    simplified: "上班",
    pinyin: "shàng bān",
    definition: "to go to work, to start work",
  },
  {
    simplified: "想像",
    pinyin: "xiǎngxiàng",
    definition: "to imagine, to visualize",
  },
  {
    simplified: "要不是",
    pinyin: "yàobúshì",
    definition: "if it were not for, but for",
  },
  { simplified: "游客", pinyin: "yóukè", definition: "tourist" },
  { simplified: "老外", pinyin: "lǎowài", definition: "foreigner (slang)" },
  { simplified: "哈", pinyin: "hā", definition: "(sound of laughter)" },
  { simplified: "对面", pinyin: "duìmiàn", definition: "opposite side" },
  { simplified: "快餐", pinyin: "kuàicān", definition: "fast food" },
  { simplified: "服装", pinyin: "fúzhuāng", definition: "clothing, apparel" },
  {
    simplified: "融入",
    pinyin: "róngrù",
    definition: "to merge into, to meld into",
  },
  {
    simplified: "特色",
    pinyin: "tèsè",
    definition: "distinguishing feature, characteristic",
  },
  {
    simplified: "保留",
    pinyin: "bǎoliú",
    definition: "to remain as before, to retain",
  },
  {
    simplified: "建筑",
    pinyin: "jiànzhù",
    definition: "architecture, to build",
  },
  { simplified: "尝", pinyin: "cháng", definition: "to taste" },
  { simplified: "小吃", pinyin: "xiǎochī", definition: "small dishes, snacks" },
  {
    simplified: "不管",
    pinyin: "bùguǎn",
    definition: "no matter, regardless of",
  },
  { simplified: "变", pinyin: "biàn", definition: "to change" },
  {
    simplified: "民以食为天",
    pinyin: "mín yǐ shí wéi tiān",
    definition: "food is as important as heaven",
  },
  {
    simplified: "句",
    pinyin: "jù",
    definition: "(measure word for sentences)",
  },
  {
    simplified: "从来",
    pinyin: "cónglái",
    definition: "from past till present, always",
  },
  { simplified: "老百姓", pinyin: "lǎobǎixìng", definition: "ordinary people" },
  {
    simplified: "尽可能",
    pinyin: "jǐn kěnéng",
    definition: "as much as possible",
  },
  { simplified: "厦", pinyin: "shà", definition: "mansion, tall building" },
  {
    simplified: "座",
    pinyin: "zuò",
    definition: "(measure word for buildings/mountains)",
  },
  { simplified: "声音", pinyin: "shēngyīn", definition: "sound, voice" },
  { simplified: "脚步", pinyin: "jiǎobù", definition: "footstep" },
  {
    simplified: "拍",
    pinyin: "pāi",
    definition: "to take a picture, to shoot a film",
  },
  { simplified: "咕噜", pinyin: "gūlū", definition: "(rumbling sound)" },
  { simplified: "法国", pinyin: "Fǎguó", definition: "France" },
  {
    simplified: "夫子庙",
    pinyin: "Fūzǐmiào",
    definition: "Temple of Confucius",
  },
];

export const vocabYunnan = [
  { simplified: "美丽", pinyin: "měilì", definition: "beautiful" },
  {
    simplified: "留（下）",
    pinyin: "liú (xia)",
    definition: "to leave behind, to stay behind",
  },
  { simplified: "深", pinyin: "shēn", definition: "deep, profound" },
  { simplified: "分享", pinyin: "fēnxiǎng", definition: "to share" },
  {
    simplified: "报名",
    pinyin: "bào míng",
    definition: "to sign up, to register",
  },
  {
    simplified: "参加",
    pinyin: "cānjiā",
    definition: "to participate, to take part",
  },
  { simplified: "团", pinyin: "tuán", definition: "group, organization" },
  {
    simplified: "包括",
    pinyin: "bāokuò",
    definition: "to include, to consist of",
  },
  {
    simplified: "交通",
    pinyin: "jiāotōng",
    definition: "transportation, traffic",
  },
  {
    simplified: "门票",
    pinyin: "ménpiào",
    definition: "admission ticket, admission fee",
  },
  { simplified: "旅客", pinyin: "lǚkè", definition: "passenger, voyager" },
  { simplified: "硬", pinyin: "yìng", definition: "hard, stiff" },
  { simplified: "卧铺", pinyin: "wòpù", definition: "sleeping bunk" },
  { simplified: "车厢", pinyin: "chēxiāng", definition: "train carriage" },
  { simplified: "软", pinyin: "ruǎn", definition: "soft" },
  { simplified: "关", pinyin: "guān", definition: "to close, to turn off" },
  { simplified: "顿", pinyin: "dùn", definition: "(measure word for meals)" },
  { simplified: "盒饭", pinyin: "héfàn", definition: "box lunch" },
  { simplified: "面", pinyin: "miàn", definition: "noodles" },
  { simplified: "幽默", pinyin: "yōumò", definition: "humorous" },
  { simplified: "省会", pinyin: "shěnghuì", definition: "provincial capital" },
  { simplified: "美", pinyin: "měi", definition: "beautiful, good" },
  { simplified: "饮食", pinyin: "yǐnshí", definition: "diet, food and drink" },
  { simplified: "风俗", pinyin: "fēngsú", definition: "custom" },
  {
    simplified: "习惯",
    pinyin: "xíguàn",
    definition: "habit, to be accustomed to",
  },
  {
    simplified: "游览",
    pinyin: "yóulǎn",
    definition: "to go sightseeing, to tour",
  },
  { simplified: "石头", pinyin: "shítou", definition: "stone, rock" },
  { simplified: "树林", pinyin: "shùlín", definition: "woods, forest" },
  { simplified: "讲", pinyin: "jiǎng", definition: "to speak, to tell" },
  { simplified: "故事", pinyin: "gùshi", definition: "story, tale" },
  { simplified: "塔", pinyin: "tǎ", definition: "tower, pagoda" },
  { simplified: "古老", pinyin: "gǔlǎo", definition: "ancient, old" },
  {
    simplified: "纪念品",
    pinyin: "jìniànpǐn",
    definition: "souvenir, keepsake",
  },
  {
    simplified: "千万",
    pinyin: "qiānwàn",
    definition: "by all means, absolutely must",
  },
  { simplified: "河", pinyin: "hé", definition: "river" },
  { simplified: "茶馆", pinyin: "cháguǎn", definition: "teahouse" },
  { simplified: "灯笼", pinyin: "dēnglong", definition: "lantern" },
  { simplified: "房东", pinyin: "fángdōng", definition: "landlord" },
  { simplified: "昆明", pinyin: "Kūnmíng", definition: "Kunming" },
  { simplified: "石林", pinyin: "Shílín", definition: "The Stone Forest" },
  { simplified: "大理", pinyin: "Dàlǐ", definition: "Dali" },
  { simplified: "丽江", pinyin: "Lìjiāng", definition: "Lijiang" },
];

export const vocabHealth = [
  { simplified: "与", pinyin: "yǔ", definition: "and, with" },
  {
    simplified: "夫妻",
    pinyin: "fūqī",
    definition: "husband and wife, couple",
  },
  { simplified: "退休", pinyin: "tuìxiū", definition: "to retire" },
  { simplified: "博物馆", pinyin: "bówùguǎn", definition: "museum" },
  {
    simplified: "不必",
    pinyin: "búbì",
    definition: "need not, do not need to",
  },
  {
    simplified: "散步",
    pinyin: "sàn bù",
    definition: "to take a walk, to go for a walk",
  },
  {
    simplified: "锻炼",
    pinyin: "duànliàn",
    definition: "to exercise, to work out",
  },
  { simplified: "广场", pinyin: "guǎngchǎng", definition: "public square" },
  { simplified: "太极拳", pinyin: "tàijíquán", definition: "tai chi" },
  {
    simplified: "早晨",
    pinyin: "zǎochen",
    definition: "morning, early morning",
  },
  {
    simplified: "成为",
    pinyin: "chéngwéi",
    definition: "to become, to turn into",
  },
  {
    simplified: "出门",
    pinyin: "chū mén",
    definition: "to go out, to leave home",
  },
  { simplified: "瑜伽", pinyin: "yújiā", definition: "yoga" },
  { simplified: "动作", pinyin: "dòngzuò", definition: "movement, action" },
  { simplified: "树", pinyin: "shù", definition: "tree" },
  {
    simplified: "重视",
    pinyin: "zhòngshì",
    definition: "to attach importance to",
  },
  {
    simplified: "注意",
    pinyin: "zhùyì",
    definition: "to pay attention to, attention",
  },
  { simplified: "等", pinyin: "děng", definition: "and so forth, etc." },
  {
    simplified: "健身房",
    pinyin: "jiànshēnfáng",
    definition: "fitness center, gym",
  },
  {
    simplified: "等于",
    pinyin: "děngyú",
    definition: "to equal, to be equivalent to",
  },
  { simplified: "减肥", pinyin: "jiǎn féi", definition: "to lose weight" },
  { simplified: "只要", pinyin: "zhǐyào", definition: "as long as, provided" },
  { simplified: "随便", pinyin: "suíbiàn", definition: "casual, careless" },
  { simplified: "即使", pinyin: "jíshǐ", definition: "even if" },
  {
    simplified: "营养",
    pinyin: "yíngyǎng",
    definition: "nutrition, nourishment",
  },
  { simplified: "饱", pinyin: "bǎo", definition: "full, satiated" },
  { simplified: "科学", pinyin: "kēxué", definition: "science, scientific" },
  { simplified: "方面", pinyin: "fāngmiàn", definition: "aspect, respect" },
  { simplified: "必须", pinyin: "bìxū", definition: "must, have to" },
  { simplified: "吸烟", pinyin: "xī yān", definition: "to smoke a cigarette" },
  { simplified: "熬夜", pinyin: "áo yè", definition: "to stay up late" },
  {
    simplified: "补充",
    pinyin: "bǔchōng",
    definition: "to supplement, to replenish",
  },
  { simplified: "睡眠", pinyin: "shuìmián", definition: "sleep" },
  {
    simplified: "只",
    pinyin: "zhī",
    definition: "(measure word for paired things)",
  },
];

export const vocabGender = [
  { simplified: "平等", pinyin: "píngděng", definition: "equal, equality" },
  {
    simplified: "重男轻女",
    pinyin: "zhòng nán qīng nǚ",
    definition:
      "to regard males as superior to females, to privilege men over women",
  },
  { simplified: "妇女", pinyin: "fùnǚ", definition: "women" },
  { simplified: "地位", pinyin: "dìwèi", definition: "position, status" },
  {
    simplified: "情况",
    pinyin: "qíngkuàng",
    definition: "situation, condition",
  },
  {
    simplified: "逐渐",
    pinyin: "zhújiàn",
    definition: "gradually, little by little",
  },
  { simplified: "机会", pinyin: "jīhuì", definition: "opportunity" },
  {
    simplified: "改革开放",
    pinyin: "gǎigé kāifàng",
    definition: "to reform and open up, Reform and Opening-Up",
  },
  { simplified: "以来", pinyin: "yǐlái", definition: "since" },
  { simplified: "企业", pinyin: "qǐyè", definition: "enterprise, business" },
  { simplified: "单位", pinyin: "dānwèi", definition: "unit" },
  { simplified: "出现", pinyin: "chūxiàn", definition: "to appear, to arise" },
  {
    simplified: "现象",
    pinyin: "xiànxiàng",
    definition: "phenomenon, appearance",
  },
  { simplified: "工厂", pinyin: "gōngchǎng", definition: "factory" },
  {
    simplified: "同工同酬",
    pinyin: "tóng gōng tóng chóu",
    definition: "equal pay for equal work",
  },
  { simplified: "女性", pinyin: "nǚxìng", definition: "female gender, woman" },
  {
    simplified: "超过",
    pinyin: "chāoguò",
    definition: "to surpass, to exceed",
  },
  { simplified: "丈夫", pinyin: "zhàngfu", definition: "husband" },
  { simplified: "妻子", pinyin: "qīzi", definition: "wife" },
  { simplified: "互相", pinyin: "hùxiāng", definition: "mutually, each other" },
  {
    simplified: "家务",
    pinyin: "jiāwù",
    definition: "household chores, household duties",
  },
  { simplified: "模范", pinyin: "mófàn", definition: "exemplary, model" },
  {
    simplified: "表现",
    pinyin: "biǎoxiàn",
    definition: "to display, to manifest",
  },
  { simplified: "男子", pinyin: "nánzǐ", definition: "man, male" },
  {
    simplified: "队",
    pinyin: "duì",
    definition: "team, a row or line of people",
  },
  { simplified: "讨厌", pinyin: "tǎoyàn", definition: "to dislike, to loathe" },
  { simplified: "队员", pinyin: "duìyuán", definition: "team member" },
  { simplified: "骄傲", pinyin: "jiāo’ào", definition: "proud, arrogant" },
  { simplified: "输", pinyin: "shū", definition: "to lose, to be defeated" },
  {
    simplified: "成绩",
    pinyin: "chéngjì",
    definition: "performance, achievement",
  },
  { simplified: "公平", pinyin: "gōngpíng", definition: "fair, just" },
  { simplified: "由", pinyin: "yóu", definition: "by" },
  { simplified: "市场", pinyin: "shìchǎng", definition: "market" },
  { simplified: "职业", pinyin: "zhíyè", definition: "occupation, profession" },
  { simplified: "薪水", pinyin: "xīnshuǐ", definition: "salary, pay" },
  { simplified: "消息", pinyin: "xiāoxi", definition: "news, message" },
  { simplified: "赢", pinyin: "yíng", definition: "to win" },
  {
    simplified: "冠军",
    pinyin: "guànjūn",
    definition: "champion, first place in a competition",
  },
  {
    simplified: "相信",
    pinyin: "xiāngxìn",
    definition: "to believe, to trust",
  },
  { simplified: "比分", pinyin: "bǐfēn", definition: "score" },
  {
    simplified: "乒乓球",
    pinyin: "pīngpāngqiú",
    definition: "ping pong, table tennis",
  },
  { simplified: "德国", pinyin: "Déguó", definition: "Germany" },
  { simplified: "西班牙", pinyin: "Xībānyá", definition: "Spain" },
];

export const vocabEnvironment = [
  {
    simplified: "保护",
    pinyin: "bǎohù",
    definition: "to protect, to safeguard",
  },
  {
    simplified: "节约",
    pinyin: "jiéyuē",
    definition: "to economize, to save",
  },
  {
    simplified: "能源",
    pinyin: "néngyuán",
    definition: "energy, energy source",
  },
  {
    simplified: "爬山",
    pinyin: "pá shān",
    definition: "to hike in the mountains, to climb a mountain",
  },
  {
    simplified: "有益",
    pinyin: "yǒuyì",
    definition: "beneficial, useful",
  },
  {
    simplified: "于",
    pinyin: "yú",
    definition: "towards, in",
  },
  {
    simplified: "段",
    pinyin: "duàn",
    definition: "measure word for section, segment",
  },
  {
    simplified: "推",
    pinyin: "tuī",
    definition: "to push, to shove",
  },
  {
    simplified: "空气",
    pinyin: "kōngqì",
    definition: "air, atmosphere",
  },
  {
    simplified: "雾霾",
    pinyin: "wùmái",
    definition: "smog",
  },
  {
    simplified: "回收",
    pinyin: "huíshōu",
    definition: "to recycle",
  },
  {
    simplified: "筒",
    pinyin: "tǒng",
    definition: "thick tube-shaped container",
  },
  {
    simplified: "扔",
    pinyin: "rēng",
    definition: "to throw, to toss",
  },
  {
    simplified: "瓶装水",
    pinyin: "píngzhuāng shuǐ",
    definition: "bottled water",
  },
  {
    simplified: "地球",
    pinyin: "dìqiú",
    definition: "the earth, the globe",
  },
  {
    simplified: "亮",
    pinyin: "liàng",
    definition: "bright, light",
  },
  {
    simplified: "太阳",
    pinyin: "tàiyáng",
    definition: "sun",
  },
  {
    simplified: "太阳能",
    pinyin: "tàiyángnéng",
    definition: "solar energy, solar power",
  },
  {
    simplified: "板",
    pinyin: "bǎn",
    definition: "board, plank",
  },
  {
    simplified: "发电",
    pinyin: "fā diàn",
    definition: "to generate electricity",
  },
  {
    simplified: "国家",
    pinyin: "guójiā",
    definition: "country, nation",
  },
  {
    simplified: "危机",
    pinyin: "wēijī",
    definition: "crisis",
  },
  {
    simplified: "风",
    pinyin: "fēng",
    definition: "wind",
  },
  {
    simplified: "石油",
    pinyin: "shíyóu",
    definition: "petroleum, oil",
  },
  {
    simplified: "煤",
    pinyin: "méi",
    definition: "coal",
  },
  {
    simplified: "规定",
    pinyin: "guīdìng",
    definition: "to regulate, to specify",
  },
  {
    simplified: "公共场所",
    pinyin: "gōnggòng chǎngsuǒ",
    definition: "public place or space",
  },
  {
    simplified: "暖气",
    pinyin: "nuǎnqì",
    definition: "heating",
  },
  {
    simplified: "温度",
    pinyin: "wēndù",
    definition: "temperature",
  },
  {
    simplified: "度",
    pinyin: "dù",
    definition: "measure word for degrees of temperature, heat",
  },
  {
    simplified: "赞成",
    pinyin: "zànchéng",
    definition: "to approve, to support",
  },
  {
    simplified: "出汗",
    pinyin: "chū hàn",
    definition: "to sweat",
  },
  {
    simplified: "餐具",
    pinyin: "cānjù",
    definition: "eating utensil, tableware",
  },
  {
    simplified: "一次性",
    pinyin: "yícìxìng",
    definition: "one-time",
  },
  {
    simplified: "砍",
    pinyin: "kǎn",
    definition: "to cut, to chop",
  },
  {
    simplified: "超市",
    pinyin: "chāoshì",
    definition: "supermarket",
  },
  {
    simplified: "塑料袋",
    pinyin: "sùliào dài",
    definition: "plastic bag",
  },
  {
    simplified: "减少",
    pinyin: "jiǎnshǎo",
    definition: "to reduce, to decrease",
  },
  {
    simplified: "污染",
    pinyin: "wūrǎn",
    definition: "to pollute, to contaminate",
  },
  {
    simplified: "造成",
    pinyin: "zào chéng",
    definition: "to cause, to give rise to",
  },
  {
    simplified: "比如",
    pinyin: "bǐrú",
    definition: "for example",
  },
  {
    simplified: "随手",
    pinyin: "suíshǒu",
    definition: "without extra effort or motion, conveniently",
  },
  {
    simplified: "加油",
    pinyin: "jiā yóu",
    definition: "to make an extra effort, to work harder",
  },
  {
    simplified: "马克",
    pinyin: "Mǎkè",
    definition: "Mark",
  },
  {
    simplified: "摄氏",
    pinyin: "Shèshì",
    definition: "Celsius, centigrade",
  },
];

export const vocabFinance = [
  { simplified: "节俭", pinyin: "jiéjiǎn", definition: "thrifty, frugal" },
  {
    simplified: "存款",
    pinyin: "cúnkuǎn",
    definition: "bank savings, to deposit money",
  },
  {
    simplified: "投资",
    pinyin: "tóu zī",
    definition: "to invest capital, investment",
  },
  { simplified: "理财", pinyin: "lǐcái", definition: "to manage wealth" },
  { simplified: "涨", pinyin: "zhǎng", definition: "to rise, to surge" },
  { simplified: "炒股", pinyin: "chǎo gǔ", definition: "to flip stocks" },
  {
    simplified: "引起",
    pinyin: "yǐnqǐ",
    definition: "to give rise to, to lead to",
  },
  {
    simplified: "思考",
    pinyin: "sīkǎo",
    definition: "to think deeply, to ponder over",
  },
  { simplified: "姑妈", pinyin: "gūmā", definition: "aunt (father’s sister)" },
  {
    simplified: "矛盾",
    pinyin: "máodùn",
    definition: "contradiction, conflict",
  },
  { simplified: "郁闷", pinyin: "yùmèn", definition: "gloomy, depressed" },
  {
    simplified: "省吃俭用",
    pinyin: "shěng chī jiǎn yòng",
    definition: "to be frugal",
  },
  {
    simplified: "笔",
    pinyin: "bǐ",
    definition: "measure word for sums of money",
  },
  { simplified: "孙子", pinyin: "sūnzi", definition: "grandson (son’s son)" },
  {
    simplified: "孙女",
    pinyin: "sūnnü",
    definition: "granddaughter (son’s daughter)",
  },
  { simplified: "未婚妻", pinyin: "wèihūnqī", definition: "fiancée" },
  {
    simplified: "算",
    pinyin: "suàn",
    definition: "to count as, to be considered as",
  },
  { simplified: "合", pinyin: "hé", definition: "to combine, to join" },
  { simplified: "劝", pinyin: "quàn", definition: "to persuade, to advise" },
  { simplified: "辛苦", pinyin: "xīnkǔ", definition: "hard, strenuous" },
  {
    simplified: "享受",
    pinyin: "xiǎngshòu",
    definition: "to enjoy, enjoyment",
  },
  { simplified: "老太太", pinyin: "lǎotàitai", definition: "elderly lady" },
  {
    simplified: "利息",
    pinyin: "lìxī",
    definition: "interest (on invested funds)",
  },
  { simplified: "增加", pinyin: "zēngjiā", definition: "to increase, to add" },
  { simplified: "老年", pinyin: "lǎonián", definition: "old age" },
  {
    simplified: "说服",
    pinyin: "shuōfú",
    definition: "to persuade, to convince",
  },
  { simplified: "签", pinyin: "qiān", definition: "to sign, to autograph" },
  { simplified: "合同", pinyin: "hétong", definition: "agreement, contract" },
  { simplified: "想法", pinyin: "xiǎngfǎ", definition: "idea, opinion" },
  { simplified: "突然", pinyin: "tūrán", definition: "suddenly, unexpectedly" },
  {
    simplified: "义工",
    pinyin: "yìgōng",
    definition: "volunteer work, volunteer",
  },
  { simplified: "麻将", pinyin: "máijàng", definition: "mahjong" },
  { simplified: "赚钱", pinyin: "zhuànqián", definition: "to make a profit" },
  { simplified: "股市", pinyin: "gǔshì", definition: "stock market" },
  { simplified: "风险", pinyin: "fēngxiǎn", definition: "risk, danger" },
  { simplified: "抵押", pinyin: "dǐyā", definition: "to mortgage" },
  { simplified: "股票", pinyin: "gǔpiào", definition: "stock, share" },
  { simplified: "跌", pinyin: "diē", definition: "to fall" },
  {
    simplified: "赔",
    pinyin: "péi",
    definition: "to lose (money, etc.), to suffer a loss",
  },
];

export const vocabvocabFinance = [
  {
    simplified: "节俭",
    pinyin: "jiéjiǎn",
    definition: "thrifty, frugal",
  },
  {
    simplified: "存款",
    pinyin: "cúnkuǎn",
    definition: "bank savings, to deposit money at a bank",
  },
  {
    simplified: "投资",
    pinyin: "tóu zī",
    definition: "to invest capital, investment",
  },
  {
    simplified: "理财",
    pinyin: "lǐcái",
    definition: "to manage wealth",
  },
  {
    simplified: "涨",
    pinyin: "zhǎng",
    definition: "to rise, to surge",
  },
  {
    simplified: "炒股",
    pinyin: "chǎo gǔ",
    definition: "to flip stocks",
  },
  {
    simplified: "引起",
    pinyin: "yǐnqǐ",
    definition: "to give rise to, to lead to",
  },
  {
    simplified: "思考",
    pinyin: "sīkǎo",
    definition: "to think deeply, to ponder over",
  },
  {
    simplified: "姑妈",
    pinyin: "gūmā",
    definition: "aunt (father’s sister)",
  },
  {
    simplified: "矛盾",
    pinyin: "máodùn",
    definition: "contradiction, conflict",
  },
  {
    simplified: "郁闷",
    pinyin: "yùmèn",
    definition: "gloomy, depressed",
  },
  {
    simplified: "省吃俭用",
    pinyin: "shěng chī jiǎn yòng",
    definition: "to be frugal",
  },
  {
    simplified: "笔",
    pinyin: "bǐ",
    definition: "measure word for sums of money",
  },
  {
    simplified: "孙子",
    pinyin: "sūnzi",
    definition: "grandson (son’s son)",
  },
  {
    simplified: "孙女",
    pinyin: "sūnnü",
    definition: "granddaughter (son’s daughter)",
  },
  {
    simplified: "未婚妻",
    pinyin: "wèihūnqī",
    definition: "fiancée",
  },
  {
    simplified: "算",
    pinyin: "suàn",
    definition: "to count as, to be considered as",
  },
  {
    simplified: "合",
    pinyin: "hé",
    definition: "to combine, to join",
  },
  {
    simplified: "劝",
    pinyin: "quàn",
    definition: "to persuade, to advise",
  },
  {
    simplified: "辛苦",
    pinyin: "xīnkǔ",
    definition: "hard, strenuous",
  },
  {
    simplified: "享受",
    pinyin: "xiǎngshòu",
    definition: "to enjoy, enjoyment",
  },
  {
    simplified: "老太太",
    pinyin: "lǎotàitai",
    definition: "elderly lady",
  },
  {
    simplified: "利息",
    pinyin: "lìxī",
    definition: "interest (on invested funds)",
  },
  {
    simplified: "增加",
    pinyin: "zēngjiā",
    definition: "to increase, to add",
  },
  {
    simplified: "老年",
    pinyin: "lǎonián",
    definition: "old age",
  },
  {
    simplified: "说服",
    pinyin: "shuōfú",
    definition: "to persuade, to convince",
  },
  {
    simplified: "签",
    pinyin: "qiān",
    definition: "to sign, to autograph",
  },
  {
    simplified: "合同",
    pinyin: "hétong",
    definition: "agreement, contract",
  },
  {
    simplified: "想法",
    pinyin: "xiǎngfǎ",
    definition: "idea, opinion",
  },
  {
    simplified: "突然",
    pinyin: "tūrán",
    definition: "suddenly, unexpectedly",
  },
  {
    simplified: "义工",
    pinyin: "yìgōng",
    definition: "volunteer work, volunteer",
  },
  {
    simplified: "麻将",
    pinyin: "májiàng",
    definition: "mahjong",
  },
  {
    simplified: "赚钱",
    pinyin: "zhuànqián",
    definition: "to make a profit",
  },
  {
    simplified: "股市",
    pinyin: "gǔshì",
    definition: "stock market",
  },
  {
    simplified: "风险",
    pinyin: "fēngxiǎn",
    definition: "risk, danger",
  },
  {
    simplified: "抵押",
    pinyin: "dǐyā",
    definition: "to mortgage",
  },
  {
    simplified: "股票",
    pinyin: "gǔpiào",
    definition: "stock, share",
  },
  {
    simplified: "跌",
    pinyin: "diē",
    definition: "to fall",
  },
  {
    simplified: "赔",
    pinyin: "péi",
    definition: "to lose (money, etc.), to suffer a loss",
  },
];

export const LESSONS: Lesson[] = [
  {
    id: "festival",
    title: "中国的节日",
    description: "Learn about Chinese holidays, festivals, and traditions.",
    vocabulary: vocabFestival,
  },
  {
    id: "change",
    title: "中国的变化",
    description: "Explore how China has modernized and changed over time.",
    vocabulary: vocabChange,
  },
  {
    id: "yunnan",
    title: "去云南旅游",
    description: "Travel through the beautiful landscapes of Yunnan province.",
    vocabulary: vocabYunnan,
  },
  {
    id: "health",
    title: "生活与健康",
    description: "Learn about healthy living habits in China.",
    vocabulary: vocabHealth,
  },
  {
    id: "gender",
    title: "男女平等",
    description: "Learn about gender equality in China.",
    vocabulary: vocabGender,
  },
  {
    id: "environment",
    title: "环境保护与节约能源",
    description:
      "Learn about environmental protection and energy conservation.",
    vocabulary: vocabEnvironment,
  },
  {
    id: "finance",
    title: "理财与投资",
    description: "Learn about financial concepts and practices.",
    vocabulary: vocabFinance,
  },
];
